// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReceiverAPI.Models;

namespace ReceiverAPI.Migrations
{
    [DbContext(typeof(ReceiverAPIContext))]
    partial class ReceiverAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReceiverAPI.Models.ReceiveModel", b =>
                {
                    b.Property<string>("titel")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("date");

                    b.HasKey("titel");

                    b.ToTable("ReceiveModel");
                });
#pragma warning restore 612, 618
        }
    }
}
